export const types = {

    USER_AUTHENTICATED: 'USER_AUTHENTICATED',

    SIGNUP: 'SIGNUP',

    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',

    GET_ROLS: 'GET_ROLS',
    ERROR_ROLS: 'ERROR_ROLS',

    UI_SET_ERROR: 'UI_SET_ERROR',
    UI_REMOVE_ERROR: 'UI_REMOVE_ERROR',

    UI_START_LOADING: 'UI_START_LOADING',
    UI_FINISH_LOADING: 'UI_FINISH_LOADING',

    ADD_CATEGORY: 'ADD_CATEGORY',
    FIND_CATEGORIES: 'FIND_CATEGORIES',
    GET_CATEGORY: 'GET_CATEGORY',
    EDIT_CATEGORY: 'EDIT_CATEGORY'
}